#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


term1 = 0
term2 = 1
sum = 0
sumOfEven = 0

while sum <4000000:
  sum = term1 + term2
  print(sum)
  term1 = term2
  term2 = sum
  if sum%2 == 0:
    sumOfEven += sum
    
    

print(sumOfEven)

